### ISSUE TITLE
ATP: Keyboard navigation in Campaigns (TFS 35876)

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/ATP-Support#61]
I need the details from TFS on this one. @Piglady64 - Would you mind giving us an assist here? I think this is something I can research to take some work off of Drew's plate. Brody mentioned it in sprint planning two weeks ago but it never made its way into a github issue. We can work on this with dev next sprint.

**Comment by humancompanion** [comment]
This ticket needs to include both drag and drop functionality (existing in ATP Campaigns) and keyboard shortcuts. The notes below are on the shortcuts. Please confirm with Margeret if the suggestions are 508 compliant. If not, its your call.

To support 508 compliance, we should create a list of tasks that are required to use Campaigns effectively and assign keyboard navigation/shortcuts to execute these tasks.

Added benefit: this could support power users to do things faster.

Examine feasibility of shortcuts for the following tasks and increased 508 compliance:

Navigation: Sets focus, either on list or card(s); Focuses on list first, and then down arrow is used to navigate into the cards to set focus on a card.
Navigate Left
 - left arrow
 - a
Navigate Right
 - right arrow
 - d
Navigate Up
 - up arrow
 - w
Navigate Down
 - down arrow
 - s

Selection: Lists or Cards must be selected to move; A single card does not need to be selected to interact with (see section below)
Select
 - Shift (single or group within list)
Bulk Select
 - Shift + navigation up/down
 - Bulk selects adjacent cards within the same list

Moving: After 1 or more cards are selected, the cards can be moved
Move Left
 - left arrow
 - a
Move Right
 - right arrow
 - d
Move Up
 - up arrow
 - w
Move Down
 - down arrow
 - s

Interaction with Object
Open Card
 - Enter
Close Card (or menu, dialogue, modal, etc.)
 - Esc
Focus
 - Achieved with navigation between cards/lists (see section above)
Remove
 - Delete
 - Backspace
Create Message (a message will be initiated for any selected cards or the selected list)
 - m could be an option

Campaigns:
Board Menu (sets focus into board banner, then arrow keys or tab can be used to select, or the following shortcuts)
 - b?
Share Menu (to colleagues)
 - @ or c (collaborate) could be options
A/C:
The info in the notes section should be used to update the AC below.

Cards can be moved from one list to another
This is done by drag and drop, or
This is done by keyboard shortcut
If an applicant card is moved to a list to a subsequent list, the "message" icon is reset to the default color/status (should this be split to another ticket?)
Card order can be changed within a list
By drag and drop
By keyboard shortcut
Shortcut to remove: delete?
Shortcut to create message:

**Comment by dreeeeewwwww** [comment]
@humancompanion did a quick mockup of what it might look like to have a menu on each card. It creates lots of `...` which, might become a little too much while scrolling down 50-100 names?

**Menu icon replaces trash icon**

<img width="490" alt="screen shot 2019-02-07 at 10 45 43 am" src="https://user-images.githubusercontent.com/13023132/52423175-8cc2a080-2ac5-11e9-9ed1-31740b7f2c06.png">

**Open card menu**

<img width="652" alt="screen shot 2019-02-07 at 10 44 32 am" src="https://user-images.githubusercontent.com/13023132/52423205-9f3cda00-2ac5-11e9-8436-31d4ea555081.png">

**Comment by humancompanion** [comment]
Perhaps when a card is selected it could obtain arrows along the side that
would be mapped to the keyboard arrow keys? Or perhaps just a “Move” option
to go alongside the two existing options?

Also, are we making a custom solution here or using a JS library for this?
I’d like to know what constraints there are.

Also, we should explore what others are doing (Trello, ZenHub, etc.)

**Comment by dreeeeewwwww** [comment]
I was just clicking around with Zenhub to see their solution and they have a vertical `...`. It works pretty well, however it only appears on hover which would nix compliance. They don't seem to let you get to it via tabbing either.

<img width="558" alt="screen shot 2019-02-07 at 11 05 36 am" src="https://user-images.githubusercontent.com/13023132/52424681-766a1400-2ac8-11e9-9eea-866178c8e742.png">

**Comment by humancompanion** [comment]
![screenshot 2019-02-08 09 51 49](https://user-images.githubusercontent.com/352987/52487691-281e4900-2b8c-11e9-84e9-4f02195c5fbe.png)

Trello makes you open the card before you can take action. So perhaps we explore actions in the header portion of the applicant panel? Then they have an explicit Actions list.

**Comment by dreeeeewwwww** [comment]
@humancompanion We don't have as many actions to perform as Trello (at least at the moment), so I tried placing them in the modal header with dropdowns (that follow suit for Trello when you go to actually move a card).

The grey button color might not be ideal, but can address that if you think this is a good direction.

<img width="916" alt="screen shot 2019-02-08 at 3 45 08 pm" src="https://user-images.githubusercontent.com/13023132/52505289-07b8b380-2bb9-11e9-8ce3-61276b562ff4.png">

<img width="859" alt="screen shot 2019-02-08 at 3 44 46 pm" src="https://user-images.githubusercontent.com/13023132/52505296-0d15fe00-2bb9-11e9-838d-b6ee84dd5d24.png">

<img width="958" alt="screen shot 2019-02-08 at 3 44 55 pm" src="https://user-images.githubusercontent.com/13023132/52505300-0f785800-2bb9-11e9-8228-4449ac50e513.png">

**Comment by dreeeeewwwww** [comment]
**TODO**
- [ ] Add move button to preview header
- [ ] Add move dropdown to preview header
- [ ] Select lets you move card to any other list
- [ ] Select lets you select the position of a card in a list numerically
- [ ] Add trash can icon to delete card
- [ ] Delete card pops up an alert modal w/ confirmation (https://usajobs.github.io/design-system/modals/)*
- [ ] *Need to add alert modal to the design system sketch file

**Comment by humancompanion** [comment]
@dreeeeewwwww - I updated the delete profile modal in the design system yesterday. I think you can just detail in the ticket that the "Delete" button would pop-up that same model with different contents and provide the content. I don't know that you need to depict it necessarily, though adding it to the Sketch file would be great.

**Comment by dreeeeewwwww** [comment]
@humancompanion I wired these together but here are the individual screens in Invision:

**Preview modal with actions**
https://opm.invisionapp.com/share/Q8OESMCYS5P#/338877567_Internship-Board-Applicant_Preview_Modal

**Opened move applicant dropdown**
https://opm.invisionapp.com/share/Q8OESMCYS5P#/345871160_Internship-Board-Applicant-Preview-Move-Card

**Delete confirmation**
https://opm.invisionapp.com/share/Q8OESMCYS5P#/346474021_Internship-Board-Delete_Applicant_Alt

**Comment by dreeeeewwwww** [comment]
- [ ] Delete - `Remove applicant from ...` we're not deleting, we're just removing from this campaign.
- [ ] Delete - text - `You won't see this person again, they won't be in the running for this campaign` reinforce not deleting data
- [ ]

**Comment by dreeeeewwwww** [comment]
@dalenard21 As part solving the keyboard navigation issues, we ended up altering the delete applicant process slightly and needed to reword the alert message you get when confirming deletion. I threw some rough things in there to start but definitely needs your input!

https://opm.invisionapp.com/share/Q8OESMCYS5P#/346474021_Internship-Board-Delete_Applicant_Alt

Text
```
**Remove applicant**
Confirm removal of applicant from your campaign.
---
Are you sure you want to remove First last name from this opportunity?  

If so, you can't undo this action. You will not see this applicant again, and they may be considered for other internship opportunities.
---
[Cancel] / [Remove]
```

**Comment by dreeeeewwwww** [comment]
@jdstill Below are the keyboard navigation mockups. We moved all of the actions you might take on a card (send message, move card, delete card) into the preview modal.

**1. Card actions in applicant preview modal (`Send message`, `Move ...`, `Remove` [trash can])**
https://opm.invisionapp.com/share/Q8OESMCYS5P#/338877567_Internship-Board-Applicant_Preview_Modal

**2. Open `Move ...` dropdown*
https://opm.invisionapp.com/share/Q8OESMCYS5P#/345871160_Internship-Board-Applicant-Preview-Move-Card

- The `List` select is populated from the names of the specific lists on each board.
- The `Position` number is based on the current number of cards in each list.

**3. Remove applicant alert modal**
https://opm.invisionapp.com/share/Q8OESMCYS5P#/346474021_Internship-Board-Delete_Applicant_Alt

**4. Card `focus` state**
https://opm.invisionapp.com/share/Q8OESMCYS5P#/346478650_Internship-Board-Small_Cards
